# version: "3.9"

# services:
#   db:
#     image: postgres:16
#     container_name: postgres_db
#     restart: always
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   app:
#     build: .
#     container_name: node_app
#     restart: always
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       GITHUB_TOKEN: ${GITHUB_TOKEN}
#     depends_on:
#       db:
#         condition: service_healthy
#     volumes:
#        - .:/src
#        - /src/node_modules

# volumes:
#   postgres_data:
#   node_modules:

version: "3.9"

services:
  # Banco local - só usado em desenvolvimento
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.dev         # Use .env.dev para dev local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Aplicação Node.js
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-.env.dev} # Variável de ambiente ENV_FILE define se é dev ou production
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SECRET: ${SECRET}
      DB_SSL: ${DB_SSL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
       - .:/src
       - /src/node_modules

volumes:
  postgres_data:
  node_modules: